/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { StockItem, OutboundItem } from '../types';

export const mockStockData: StockItem[] = [
  {
    id: '5',
    date: '2026-03-10',
    category: '服务器',
    productType: '服务器整机',
    productName: '机架式服务器',
    brand: '华为',
    spec: '2288H V5',
    materialCode: 'SERVER-001',
    serialNumber: 'SN-IN-0005',
    quantity: 3,
    unit: '台',
    warehouse: '名美301机房',
  },
  {
    id: '4',
    date: '2026-03-08',
    category: '存储',
    productType: '存储配件',
    productName: 'SAS硬盘',
    brand: '华为',
    spec: '10TB 7.2K RPM NL-SAS',
    materialCode: 'DISK-001',
    serialNumber: 'SN-IN-0004',
    quantity: 12,
    unit: '块',
    warehouse: '名美203机房',
  },
  {
    id: '3',
    date: '2026-03-05',
    category: '防火墙',
    productType: '防火墙整机',
    productName: '边界防火墙',
    brand: '华为',
    spec: 'USG6620E-K',
    materialCode: 'FW-001',
    serialNumber: 'SN-IN-0003',
    quantity: 1,
    unit: '台',
    warehouse: '名美301机房',
  },
  {
    id: '2',
    date: '2026-03-03',
    category: '交换机',
    productType: '交换机配件',
    productName: '光模块',
    brand: '华为',
    spec: '10G单模模块80KM',
    materialCode: 'MODULE-001',
    serialNumber: 'SN-IN-0002',
    quantity: 10,
    unit: '个',
    warehouse: '名美203机房',
  },
  {
    id: '1',
    date: '2026-03-01',
    category: '交换机',
    productType: '交换机整机',
    productName: '接入交换机',
    brand: '华为',
    spec: 'CE6857F-48S6CQ',
    materialCode: 'SWITCH-001',
    serialNumber: 'SN-IN-0001',
    quantity: 2,
    unit: '台',
    warehouse: '名美203机房',
  },
];

export const mockOutboundData: OutboundItem[] = [
  {
    id: '3',
    date: '2026-03-18',
    serialNumber: 'SN-IN-0004',
    productName: 'SAS硬盘',
    brand: '华为',
    spec: '10TB 7.2K RPM NL-SAS',
    materialCode: 'DISK-001',
    quantity: 4,
    purpose: '存储扩容',
    warehouse: '名美203机房',
    department: '基础设施部',
  },
  {
    id: '2',
    date: '2026-03-15',
    serialNumber: 'SN-IN-0003',
    productName: '边界防火墙',
    brand: '华为',
    spec: 'USG6620E-K',
    materialCode: 'FW-001',
    quantity: 1,
    purpose: '项目部署',
    warehouse: '名美301机房',
    department: '安全运维部',
  },
  {
    id: '1',
    date: '2026-03-12',
    serialNumber: 'SN-IN-0002',
    productName: '光模块',
    brand: '华为',
    spec: '10G单模模块80KM',
    materialCode: 'MODULE-001',
    quantity: 2,
    purpose: '交换机扩容',
    warehouse: '名美203机房',
    department: '网络运维部',
  },
];
