/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { StockItem, OutboundItem } from '../types';

export const mockStockData: StockItem[] = [
  {
    id: 5,
    inbound_date: '2026-03-10',
    major_category: '服务器',
    product_type: '服务器整机',
    product_name: '机架式服务器',
    product_brand: '华为',
    product_spec: '2288H V5',
    material_code: 'SERVER-001',
    serial_number: 'SN-IN-0005',
    inbound_qty: 3,
    unit: '台',
    inbound_room: '名美301机房',
  },
  {
    id: 4,
    inbound_date: '2026-03-08',
    major_category: '存储',
    product_type: '存储配件',
    product_name: 'SAS硬盘',
    product_brand: '华为',
    product_spec: '10TB 7.2K RPM NL-SAS',
    material_code: 'DISK-001',
    serial_number: 'SN-IN-0004',
    inbound_qty: 12,
    unit: '块',
    inbound_room: '名美203机房',
  },
  {
    id: 3,
    inbound_date: '2026-03-05',
    major_category: '防火墙',
    product_type: '防火墙整机',
    product_name: '边界防火墙',
    product_brand: '华为',
    product_spec: 'USG6620E-K',
    material_code: 'FW-001',
    serial_number: 'SN-IN-0003',
    inbound_qty: 1,
    unit: '台',
    inbound_room: '名美301机房',
  },
  {
    id: 2,
    inbound_date: '2026-03-03',
    major_category: '交换机',
    product_type: '交换机配件',
    product_name: '光模块',
    product_brand: '华为',
    product_spec: '10G单模模块80KM',
    material_code: 'MODULE-001',
    serial_number: 'SN-IN-0002',
    inbound_qty: 10,
    unit: '个',
    inbound_room: '名美203机房',
  },
  {
    id: 1,
    inbound_date: '2026-03-01',
    major_category: '交换机',
    product_type: '交换机整机',
    product_name: '接入交换机',
    product_brand: '华为',
    product_spec: 'CE6857F-48S6CQ',
    material_code: 'SWITCH-001',
    serial_number: 'SN-IN-0001',
    inbound_qty: 2,
    unit: '台',
    inbound_room: '名美203机房',
  },
];

export const mockOutboundData: OutboundItem[] = [
  {
    id: 3,
    outbound_date: '2026-03-18',
    product_serial_number: 'SN-IN-0004',
    product_name: 'SAS硬盘',
    product_brand: '华为',
    product_spec: '10TB 7.2K RPM NL-SAS',
    material_code: 'DISK-001',
    outbound_qty: 4,
    usage_purpose: '存储扩容',
    target_room: '名美203机房',
    owner_org: '基础设施部',
  },
  {
    id: 2,
    outbound_date: '2026-03-15',
    product_serial_number: 'SN-IN-0003',
    product_name: '边界防火墙',
    product_brand: '华为',
    product_spec: 'USG6620E-K',
    material_code: 'FW-001',
    outbound_qty: 1,
    usage_purpose: '项目部署',
    target_room: '名美301机房',
    owner_org: '安全运维部',
  },
  {
    id: 1,
    outbound_date: '2026-03-12',
    product_serial_number: 'SN-IN-0002',
    product_name: '光模块',
    product_brand: '华为',
    product_spec: '10G单模模块80KM',
    material_code: 'MODULE-001',
    outbound_qty: 2,
    usage_purpose: '交换机扩容',
    target_room: '名美203机房',
    owner_org: '网络运维部',
  },
];
